name: Montshe Mokgokong
title: Montshe's blog
email: mokgokongjohannes@gmail.com
theme: jekyll-theme-cayman
description: Hi there.. My name is Montshe Mokgokong, I am on journey to software craftsmanship,I'll be writing about the things I've learned and the projects I've completed..Happy reading!
